### ISSUE TITLE
The alignment function when there are Chinese characters

### ISSUE THREAD

**Issue by kdurant** [SCJangra/table-nvim#4]
![image](https://github.com/user-attachments/assets/32f481be-5d87-4701-9a84-ec82adfd529c)

![image](https://github.com/user-attachments/assets/4eafd4cb-30af-41ee-9100-a2b75e54ccab)

**Comment by SCJangra** [comment]
Just pushed a fix for this, check out if it's working.

**Comment by kdurant** [comment]
![image](https://github.com/user-attachments/assets/f2022f5f-07c4-459d-8e31-661633df8f42)



![image](https://github.com/user-attachments/assets/4accea27-8427-40d4-ae3d-da7403ae8b65)

**Comment by SCJangra** [comment]
That seems strange to me. Did you by change paste the new text in `Normal` mode? Currently there is a limitation that the table only formats (aligns automatically) when come out of the `Insert` mode. So for example, if you delete a word using `dw` or `diw`, it won't automatically realign that table because you never got into `Insert` mode.

**Comment by SCJangra** [comment]
Closed accidentally

**Comment by kdurant** [comment]
No
1.  press `i` 
2. enter chinese characters
3. `<Esc>`
4. `:wq`

**Comment by kdurant** [comment]
thanks
